### ISSUE TITLE
Additional lightWhenOff and lightWhenOn NBT Data after placing and breaking old prints causes them to not stack

### ISSUE THREAD

**Issue by creeloper27** [SwitchCraftCC/sc-peripherals#42] opened 2024-03-15 16:08 UTC
This is probably related to #41 but seems like a different problem.

While investigating #41 I realized that my old (created a few months ago) 3d prints get additional NBT data after I place and break them, this causes them to not stack with my old ones that I never placed.

The reason seems to be some addional NBT Data `lightWhenOff` and `lightWhenOn` that gets added to the prints after I place and break them.

Example:
`black.3dj`
```
{
    "label": "black",
    "isButton": false,
    "collideWhenOn": true,
    "collideWhenOff": true,
    "lightLevel": 0,
    "redstoneLevel": 0,
    "shapesOff": [
        { "bounds": [0,0,0,16,16,16], "texture": "sc-peripherals:block/white", "tint": "000000"}
    ],
    "shapesOn": []
}
```
old `black.3dj` print (from a few months ago) that never got placed:
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/60a568b5-e539-4eef-898e-a16578068f2f)

old `black.3dj` print (from a few months ago) that I placed and broke a few minutes ago:
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/0e3e24c5-5fc9-47ef-86d5-747edf495687)

**Comment by Lemmmy** [comment] 2024-03-15 18:53
Duplicate of #41

**Closed as not planned by Lemmmy** 2024-03-15 18:53 UTC
Labels: duplicate
